name: Quality

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

permissions: 
  contents: read

jobs:
  format:
    name: Run gofmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Check gofmt
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go files are not formatted. Run 'gofmt -w .' to fix them."
            exit 1
          fi

  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
            go-version-file: 'go.mod'
            cache: false

      - name: Prepare build cache
        run: make prepare

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: v2.11.4

  verify:
    name: Run go vet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version-file: 'go.mod'
          cache: false

      - name: Vet
        run: make vet